version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: github_search_engine_development
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/myapp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: github_search_engine_development
      POSTGRESS_HOST: db
      POSTGRESS_PORT: '5432'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - migration
      - redis
      - elasticsearch
    command: ["rails", "server", "-b", "0.0.0.0"]
  redis:
    image: redis
    volumes:
      - redis:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    expose:
      - '9200'
      - '9300'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - app-network

  migration:
    build: .
    volumes:
      - .:/myapp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: github_search_engine_development
      POSTGRESS_HOST: db
      POSTGRESS_PORT: '5432'
    command: ["rails", "db:migrate"]
    depends_on:
      - db
volumes:
  postgres:
  redis:
networks:
  app-network:
    driver: bridge
