default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRESS_HOST"] %>
  port: <%= ENV["POSTGRESS_PORT"] %>

development:
  <<: *default


test:
  <<: *default


production:
  <<: *default
